
# Points to Docker Postgres
edc.datasource.default.url=jdbc:postgresql://localhost:5432/edc
edc.datasource.default.driver-class-name=org.postgresql.Driver
edc.datasource.default.user=postgres
edc.datasource.default.password=edc123

# Pool settings
edc.datasource.default.pool.maximum-pool-size=20
edc.datasource.default.pool.minimum-idle=5