# SQL Data Source
edc.datasource.url=jdbc:postgresql://localhost:5432/edcdb
edc.datasource.username=edc_user
edc.datasource.password=secret
edc.datasource.driverClassName=org.postgresql.Driver

# SQL dialect
edc.sql.dialect=POSTGRES
